config/routes.rb
Rails.application.routes.draw do
  root 'tv_shows#index'

  resources :tv_shows, only: [:index, :show]

  resources :tv_shows do
    member do
      get :view_it
      get :search_results
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

# ApplicationRecord
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tv_show.rb
# frozen_string_literal: true

class TvShow < ApplicationRecord
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/tv_shows_controller.rb
# frozen_string_literal: true

# rubocop:disable Metrics/LineLength

# TvShowController
class TvShowsController < ApplicationController
  require 'cgi'
  require 'uri'
  before_action :set_tv_show, only: %i[show edit update destroy]

  # GET /tv_shows
  # GET /tv_shows.json
  def index
    endpoint = "https://api.themoviedb.org/3/discover/tv?api_key=#{set_api_key}&language=en-US&sort_by=popularity.desc&page=1&timezone=America%2FNew_York&include_null_first_air_dates=false"

    response = HTTParty.get(endpoint)

    @tv_shows = response['results']
  end

  # GET /tv_shows/1
  # GET /tv_shows/1.json
  def show; end

  # GET /tv_shows/new
  def new
    @tv_show = TvShow.new
  end

  # GET /tv_shows/1/edit
  def edit; end

  # POST /tv_shows
  # POST /tv_shows.json
  def create
    @tv_show = TvShow.new(tv_show_params)

    respond_to do |format|
      if @tv_show.save
        format.html { redirect_to @tv_show, notice: 'Tv show was successfully created.' }
        format.json { render :show, status: :created, location: @tv_show }
      else
        format.html { render :new }
        format.json { render json: @tv_show.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tv_shows/1
  # PATCH/PUT /tv_shows/1.json
  def update
    respond_to do |format|
      if @tv_show.update(tv_show_params)
        format.html { redirect_to @tv_show, notice: 'Tv show was successfully updated.' }
        format.json { render :show, status: :ok, location: @tv_show }
      else
        format.html { render :edit }
        format.json { render json: @tv_show.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tv_shows/1
  # DELETE /tv_shows/1.json
  def destroy
    @tv_show.destroy
    respond_to do |format|
      format.html { redirect_to tv_shows_url, notice: 'Tv show was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def view_it
    tv_show_id = request.original_url.split('/')[4]
    @tv_show = HTTParty.get("https://api.themoviedb.org/3/tv/#{tv_show_id}?api_key=#{set_api_key}&language=en-US")
    render template: 'tv_shows/_the_tv_show'
  end

  def search_results
    search_query = request.original_url
                          .split('/')
                          .last
                          .match(/query=([^&]*)/)[1]

    search_endpoint = "https://api.themoviedb.org/3/search/tv?api_key=#{set_api_key}&language=en-US&query=#{search_query}&page=1"
    @search_results = HTTParty.get(search_endpoint)
    render template: 'tv_shows/_search_results'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_tv_show
    @tv_show = TvShow.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def tv_show_params
    params.require(:tv_show).permit(:name)
  end

  def set_api_key
    ENV['MOVIE_DB_API_KEY']
  end
end

# rubocop:enable Metrics/LineLength

app/helpers/application_helper.rb
# frozen_string_literal: true

# ApplicationHelper
module ApplicationHelper
end

app/helpers/tv_shows_helper.rb
# frozen_string_literal: true

# TvShowsHelper
module TvShowsHelper
end

app/views/layouts/_search.erb
<%= javascript_include_tag "searcher" %>

<div class="row">
  <div class="col s12">
    <div class="row">
      <div class="input-field col s12">
        <i class="material-icons prefix">search</i>
        <input type="text" id="autocomplete-input" class="autocomplete">
        <label for="autocomplete-input">Search...</label>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_title.erb
<h1 class="center-align">
  <a class="header" href="/">
    BLOCBUSTER TV
  </a>
</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blocbuster</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="">
      <%= yield %>
    </div>
  </body>
</html>

app/views/tv_shows/_form.html.erb
<%= form_with(model: tv_show, local: true) do |form| %>
  <% if tv_show.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tv_show.errors.count, "error") %> prohibited this tv_show from being saved:</h2>

      <ul>
      <% tv_show.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tv_shows/_search_results.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <%= render "layouts/title" %>
  <%= render "layouts/search" %>
  <% if @search_results["results"].length > 0 %>
  <div class="row">
    <div class="col s12">
      <div class="card grey darken-4">
        <div class="card-content white-text">
          <span class="">Search Results</span>
        </div>
        <div class="card-action">
          <a href="#" onclick="location.href = document.referrer; return false;">Go Back</a>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <% @search_results["results"].each_with_index do |search_result, index| %>
    <div class="col s12 m6 l4">
      <div class="card medium black white-text hoverable">
        <%= link_to view_it_tv_show_path(search_result["id"]) do %>
          <div class="card-image">
            <% if search_result["backdrop_path"] %>
              <div class="img-fade">
                <img src="https://image.tmdb.org/t/p/w500<%= search_result["backdrop_path"] %>">
              </div>
              <% elsif search_result["poster_path"] %>
              <div class="poster-container">
                <div class="poster-fade cropper">
                  <img src="https://image.tmdb.org/t/p/w500<%= search_result["poster_path"] %>">
                </div>
              </div>
              <% else %>
              <div class="img-fade">
                <img src="https://c.na72.content.force.com/servlet/servlet.ImageServer?id=0151H000004FM1FQAW&oid=00DA0000000Zzoi">
              </div>
              <% end %>
            <span class="card-title name"><%= search_result["name"] %></span>
          </div>
        <% end %>
        <div class="overview-text">
          <%= search_result["overview"][0..300] + '...' %>
          <%= link_to 'MORE', view_it_tv_show_path(search_result["id"]) %>
          <span class="invisible-tv-show-ids"><%= search_result["id"] %></span>
        </div>
      </div>
    </div>
    <% end %>
  </div>
  <% else %>
  <div class="row">
    <div class="col s12">
      <div class="card grey darken-4">
        <div class="card-content white-text">
          <h3 class="flow-text">No Results for this serch term. Try again!</h3>
        </div>
      </div>
    </div>
  </div>
  <% end %>



</div>

app/views/tv_shows/_search_results.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <%= render "layouts/title" %>
  <%= render "layouts/search" %>
  <% if @search_results["results"].length > 0 %>
  <div class="row">
    <div class="col s12">
      <div class="card grey darken-4">
        <div class="card-content white-text">
          <span class="">Search Results</span>
        </div>
        <div class="card-action">
          <a href="#" onclick="location.href = document.referrer; return false;">Go Back</a>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <% @search_results["results"].each_with_index do |search_result, index| %>
    <div class="col s12 m6 l4">
      <div class="card medium black white-text hoverable">
        <%= link_to view_it_tv_show_path(search_result["id"]) do %>
          <div class="card-image">
            <% if search_result["backdrop_path"] %>
              <div class="img-fade">
                <img src="https://image.tmdb.org/t/p/w500<%= search_result["backdrop_path"] %>">
              </div>
              <% elsif search_result["poster_path"] %>
              <div class="poster-container">
                <div class="poster-fade cropper">
                  <img src="https://image.tmdb.org/t/p/w500<%= search_result["poster_path"] %>">
                </div>
              </div>
              <% else %>
              <div class="img-fade">
                <img src="https://c.na72.content.force.com/servlet/servlet.ImageServer?id=0151H000004FM1FQAW&oid=00DA0000000Zzoi">
              </div>
              <% end %>
            <span class="card-title name"><%= search_result["name"] %></span>
          </div>
        <% end %>
        <div class="overview-text">
          <%= search_result["overview"][0..300] + '...' %>
          <%= link_to 'MORE', view_it_tv_show_path(search_result["id"]) %>
          <span class="invisible-tv-show-ids"><%= search_result["id"] %></span>
        </div>
      </div>
    </div>
    <% end %>
  </div>
  <% else %>
  <div class="row">
    <div class="col s12">
      <div class="card grey darken-4">
        <div class="card-content white-text">
          <h3 class="flow-text">No Results for this serch term. Try again!</h3>
        </div>
      </div>
    </div>
  </div>
  <% end %>



</div>

app/views/tv_shows/_the_tv_show.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <%= render "layouts/title" %>
  <%= render "layouts/search" %>
  <div class="col s12">
    <div class="row">
      <div class="col s12">
        <div class="card-action border-none left-align">
          <a class="waves-effect waves-light btn red darken-3 box-shadow" href="/">Home</a>
        </div>
      </div>
      <div class="col s12">
        <div class="card large horizontal">
          <div class="card-image responsive-img">
            <% if @tv_show["poster_path"] %>
              <img src="https://image.tmdb.org/t/p/w500<%= @tv_show["poster_path"] %>">
            <% elsif %>
              <img src="https://image.tmdb.org/t/p/w500<%= @tv_show["backdrop_path"] %>">
            <% else %>
              <img src="https://c.na72.content.force.com/servlet/servlet.ImageServer?id=0151H000004FM1FQAW&oid=00DA0000000Zzoi">
            <% end %>
          </div>
          <div class="card-stacked">
            <div class="card-content">
              <h5><%= @tv_show["name"] %></h5>
              <p><%= @tv_show["overview"] %></p>

              <% if @tv_show["created_by"].length > 0 %>
              <h5>Creators:</h5>
                <% creators = [] %>
                <% @tv_show["created_by"].each do |creator| %>
                  <% creators.push(creator["name"]) %>
                <% end %>
                <%= creators.join(', ') %>
              <% end %>

              <% if @tv_show["networks"].length > 0 %>
                <h5>Watch on:</h5>
                <% networks = [] %>
                <% @tv_show["networks"].each do |network| %>
                  <% networks.push(network["name"]) %>
                <% end %>
                <% if networks.length > 0 %>
                  <%= networks.join(', ') + ", YouTube" %>
                <% else %>
                  <%= "YouTube" %>
                <% end %>
              <% end %>

            </div>
            <div class="card-action border-none right-align">
              <a class="waves-effect waves-light btn red darken-3 box-shadow"
                 href="https://www.youtube.com/results?search_query=watch%20<%= @tv_show["name"] %>%20tv%20show"
                 target="_blank">
                 Watch Now
               </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/tv_shows/_the_tv_show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <%= render "layouts/title" %>
  <%= render "layouts/search" %>
  <div class="col s12">
    <div class="row">
      <div class="col s12">
        <div class="card-action border-none left-align">
          <a class="waves-effect waves-light btn red darken-3 box-shadow" href="/">Home</a>
        </div>
      </div>
      <div class="col s12">
        <div class="card large horizontal">
          <div class="card-image responsive-img">
            <% if @tv_show["poster_path"] %>
              <img src="https://image.tmdb.org/t/p/w500<%= @tv_show["poster_path"] %>">
            <% elsif %>
              <img src="https://image.tmdb.org/t/p/w500<%= @tv_show["backdrop_path"] %>">
            <% else %>
              <img src="https://c.na72.content.force.com/servlet/servlet.ImageServer?id=0151H000004FM1FQAW&oid=00DA0000000Zzoi">
            <% end %>
          </div>
          <div class="card-stacked">
            <div class="card-content">
              <h5><%= @tv_show["name"] %></h5>
              <p><%= @tv_show["overview"] %></p>

              <% if @tv_show["created_by"].length > 0 %>
              <h5>Creators:</h5>
                <% creators = [] %>
                <% @tv_show["created_by"].each do |creator| %>
                  <% creators.push(creator["name"]) %>
                <% end %>
                <%= creators.join(', ') %>
              <% end %>

              <% if @tv_show["networks"].length > 0 %>
                <h5>Watch on:</h5>
                <% networks = [] %>
                <% @tv_show["networks"].each do |network| %>
                  <% networks.push(network["name"]) %>
                <% end %>
                <% if networks.length > 0 %>
                  <%= networks.join(', ') + ", YouTube" %>
                <% else %>
                  <%= "YouTube" %>
                <% end %>
              <% end %>

            </div>
            <div class="card-action border-none right-align">
              <a class="waves-effect waves-light btn red darken-3 box-shadow"
                 href="https://www.youtube.com/results?search_query=watch%20<%= @tv_show["name"] %>%20tv%20show"
                 target="_blank">
                 Watch Now
               </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/tv_shows/edit.html.erb
<h1>Editing Tv Show</h1>

<%= render 'form', tv_show: @tv_show %>

<%= link_to 'Show', @tv_show %> |
<%= link_to 'Back', tv_shows_path %>

app/views/tv_shows/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <%= render "layouts/title" %>
  <%= render "layouts/search" %>
  <div class="row">
    <div class="col s12">
      <div class="card red accent-4">
        <div class="card-content white-text center-align">
          <span class="flow-text">Popular Shows</span>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <% @tv_shows.each_with_index do |tv_show, index| %>
    <div class="col s12 m6 l4">
      <div class="card medium black white-text hoverable">
        <%= link_to view_it_tv_show_path(tv_show["id"]) do %>
          <div class="card-image">
            <div class="img-fade">
              <img src="https://image.tmdb.org/t/p/w500<%= tv_show["backdrop_path"] %>">
            </div>
            <span class="card-title name"><%= tv_show["name"] %></span>
          </div>
        <% end %>
        <div class="overview-text">
          <%= tv_show["overview"][0..300] + '...' %>
          <%= link_to 'MORE', view_it_tv_show_path(tv_show["id"]) %>
          <span class="invisible-tv-show-ids"><%= tv_show["id"] %></span>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/tv_shows/new.html.erb
<h1>New Tv Show</h1>

<%= render 'form', tv_show: @tv_show %>

<%= link_to 'Back', tv_shows_path %>

app/views/tv_shows/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @tv_show.name %>
</p>

<%= link_to 'Edit', edit_tv_show_path(@tv_show) %> |
<%= link_to 'Back', tv_shows_path %>